#pragma once
enum Direction {UP,DOWN,RIGHT,LEFT};
enum MainMenu {STORE=9,INVENTORY,SHIP_MAINTAIN,DEPARTURE,EXIT,MAIN_ETC};
enum DRAW { IS_MAIN, IS_STORE,IS_WEAPON,IS_INVENTORY};
enum StoreMenu { WEAPON, PROTECT,SHIP,POTION,STORE_ETC,STORE_EXIT};
enum Weapon {SHIMETER=11,KATANA,HILAND,GUN, WEAPON_EXIT,WEAPON_ETC,};
enum ItemAct{USE=1,UNUSE,ENHANCEMENT};