#pragma once
enum Direction {UP,DOWN,RIGHT,LEFT};
enum MainMenu {STORE=8,INVENTORY,SHIP_MAINTAIN,DEPARTURE,EXIT,MAIN_ETC};
enum DRAW { IS_MAIN, IS_STORE};
enum StoreMenu { WEAPON, PROTECT,SHIP,POTION,STORE_ETC,STORE_EXIT};